language: node_js
node_js:
    - "7.10"
    - "8"
    - "10"
    - "11"
sudo: false
script:
    - npm run lint
    - npm run test-ci
after_script:
    - |
      npm install --save-dev coveralls
      coveralls < ./coverage/lcov.info
